server:
  port: 9001
#数据库相关配置:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.7.231:3306/filedatabase?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: CaoHao_(1224819118)
    #解析resources/静态资源
    mvc:
      static-path-pattern: /**
logging:
  level:
    root: warn
    com.lrm: info
  file: log/blog-pro.log

